language: python
python:
  - 3.6.5

#check code
script:
  - build_consumer.sh
  - pylint --rcfile=.pylintrc consumer/
  - build_producer.sh
  - pylint --rcfile=.pylintrc producer/

# command to install dependencies
install:
  - pip install pylint
  - pip install -r consumer/requirements.txt
  - pip install -r producer/requirements.txt
