language: python
python:
  - 3.6.5

#check code
script:
  - pylint --rcfile=.pylintrc heat_map_training/
  - pylint --rcfile=.pylintrc tests/

# command to install dependencies
install:
  - pip install -r requirements.txt
