version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
     - "8080:5672"
     - "9090:15672"
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    image: consumer:latest
    depends_on:
     - rabbit
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    image: producer:latest
    ports:
     - "8000:8000"
    depends_on:
     - rabbit
  
