version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
     - "8080:5672"
     - "9090:15672"
  fluentd:
    image: "fluent/fluentd"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - /data:/fluentd/log
  consumer:
    build:
      context: ./
      dockerfile: /consumer/Dockerfile
    image: consumer:latest
    depends_on:
     - rabbit
     - fluentd
  producer:
    build:
      context: ./
      dockerfile: /producer/Dockerfile
    image: producer:latest
    ports:
     - "8000:8000"
    depends_on:
     - rabbit
     - fluentd
