version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
     - "8080:5672"
     - "9090:15672"
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    image: consumer:latest
    depends_on:
     - rabbit
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    image: producer:latest
    ports:
     - "8000:8000"
    depends_on:
     - rabbit

