version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
     - "8080:5672"
     - "9090:15672"
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: postgres:customized
    ports:
     - "7070:5432"
  fluentd:
    image: "fluent/fluentd"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - /data:/fluentd/log
  consumer:
    build:
      context: ./
      dockerfile: ./consumer/Dockerfile
    image: consumer:latest
    depends_on:
     - rabbit
     - fluentd
  producer:
    build:
      context: ./
      dockerfile: ./producer/Dockerfile
    image: producer:latest
    ports:
     - "8000:8000"
    depends_on:
     - rabbit
     - postgres
     - fluentd
