# data to use in mock response to test bitbucket
REPO_DATA = {'id': 136896178, 'node_id': 'MDEwOlJlcG9zaXRvcnkxMzY4OTYxNzg=', 'name': 'test1',
             'full_name': 'BoartK/test1',
             'owner': {'login': 'BoartK', 'id': 39279178, 'node_id': 'MDQ6VXNlcjM5Mjc5MTc4',
                       'avatar_url': 'https://avatars3.githubusercontent.com/u/39279178?v=4',
                       'gravatar_id': '', 'url': 'https://api.github.com/users/BoartK',
                       'html_url': 'https://github.com/BoartK',
                       'followers_url': 'https://api.github.com/users/BoartK/followers',
                       'following_url': 'https://api.github.com/users/BoartK/following{/other_user}',
                       'gists_url': 'https://api.github.com/users/BoartK/gists{/gist_id}',
                       'starred_url': 'https://api.github.com/users/BoartK/starred{/owner}{/repo}',
                       'subscriptions_url': 'https://api.github.com/users/BoartK/subscriptions',
                       'organizations_url': 'https://api.github.com/users/BoartK/orgs',
                       'repos_url': 'https://api.github.com/users/BoartK/repos',
                       'events_url': 'https://api.github.com/users/BoartK/events{/privacy}',
                       'received_events_url': 'https://api.github.com/users/BoartK/received_events',
                       'type': 'User', 'site_admin': False}, 'private': False,
             'html_url': 'https://github.com/BoartK/test1', 'description': '123', 'fork': False,
             'url': 'https://api.github.com/repos/BoartK/test1',
             'forks_url': 'https://api.github.com/repos/BoartK/test1/forks',
             'keys_url': 'https://api.github.com/repos/BoartK/test1/keys{/key_id}',
             'collaborators_url': 'https://api.github.com/repos/BoartK/test1/collaborators{/collaborator}',
             'teams_url': 'https://api.github.com/repos/BoartK/test1/teams',
             'hooks_url': 'https://api.github.com/repos/BoartK/test1/hooks',
             'issue_events_url': 'https://api.github.com/repos/BoartK/test1/issues/events{/number}',
             'events_url': 'https://api.github.com/repos/BoartK/test1/events',
             'assignees_url': 'https://api.github.com/repos/BoartK/test1/assignees{/user}',
             'branches_url': 'https://api.github.com/repos/BoartK/test1/branches{/branch}',
             'tags_url': 'https://api.github.com/repos/BoartK/test1/tags',
             'blobs_url': 'https://api.github.com/repos/BoartK/test1/git/blobs{/sha}',
             'git_tags_url': 'https://api.github.com/repos/BoartK/test1/git/tags{/sha}',
             'git_refs_url': 'https://api.github.com/repos/BoartK/test1/git/refs{/sha}',
             'trees_url': 'https://api.github.com/repos/BoartK/test1/git/trees{/sha}',
             'statuses_url': 'https://api.github.com/repos/BoartK/test1/statuses/{sha}',
             'languages_url': 'https://api.github.com/repos/BoartK/test1/languages',
             'stargazers_url': 'https://api.github.com/repos/BoartK/test1/stargazers',
             'contributors_url': 'https://api.github.com/repos/BoartK/test1/contributors',
             'subscribers_url': 'https://api.github.com/repos/BoartK/test1/subscribers',
             'subscription_url': 'https://api.github.com/repos/BoartK/test1/subscription',
             'commits_url': 'https://api.github.com/repos/BoartK/test1/commits{/sha}',
             'git_commits_url': 'https://api.github.com/repos/BoartK/test1/git/commits{/sha}',
             'comments_url': 'https://api.github.com/repos/BoartK/test1/comments{/number}',
             'issue_comment_url': 'https://api.github.com/repos/BoartK/test1/issues/comments{/number}',
             'contents_url': 'https://api.github.com/repos/BoartK/test1/contents/{+path}',
             'compare_url': 'https://api.github.com/repos/BoartK/test1/compare/{base}...{head}',
             'merges_url': 'https://api.github.com/repos/BoartK/test1/merges',
             'archive_url': 'https://api.github.com/repos/BoartK/test1/{archive_format}{/ref}',
             'downloads_url': 'https://api.github.com/repos/BoartK/test1/downloads',
             'issues_url': 'https://api.github.com/repos/BoartK/test1/issues{/number}',
             'pulls_url': 'https://api.github.com/repos/BoartK/test1/pulls{/number}',
             'milestones_url': 'https://api.github.com/repos/BoartK/test1/milestones{/number}',
             'notifications_url': 'https://api.github.com/repos/BoartK/test1/notifications{?since,all,participating}',
             'labels_url': 'https://api.github.com/repos/BoartK/test1/labels{/name}',
             'releases_url': 'https://api.github.com/repos/BoartK/test1/releases{/id}',
             'deployments_url': 'https://api.github.com/repos/BoartK/test1/deployments',
             'created_at': '2018-06-11T08:22:58Z', 'updated_at': '2018-06-11T08:54:20Z',
             'pushed_at': '2018-06-11T08:59:13Z', 'git_url': 'git://github.com/BoartK/test1.git',
             'ssh_url': 'git@github.com:BoartK/test1.git',
             'clone_url': 'https://github.com/BoartK/test1.git',
             'svn_url': 'https://github.com/BoartK/test1', 'homepage': None, 'size': 7,
             'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python', 'has_issues': True,
             'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
             'forks_count': 0, 'mirror_url': None, 'archived': False, 'open_issues_count': 1,
             'license': None, 'forks': 0, 'open_issues': 1, 'watchers': 0,
             'default_branch': 'master', 'network_count': 0, 'subscribers_count': 0}

CONT_DATA = [{'login': 'mixa1901', 'id': 26742260, 'node_id': 'MDQ6VXNlcjI2NzQyMjYw',
              'avatar_url': 'https://avatars0.githubusercontent.com/u/26742260?v=4',
              'gravatar_id': '', 'url': 'https://api.github.com/users/mixa1901',
              'html_url': 'https://github.com/mixa1901',
              'followers_url': 'https://api.github.com/users/mixa1901/followers',
              'following_url': 'https://api.github.com/users/mixa1901/following{/other_user}',
              'gists_url': 'https://api.github.com/users/mixa1901/gists{/gist_id}',
              'starred_url': 'https://api.github.com/users/mixa1901/starred{/owner}{/repo}',
              'subscriptions_url': 'https://api.github.com/users/mixa1901/subscriptions',
              'organizations_url': 'https://api.github.com/users/mixa1901/orgs',
              'repos_url': 'https://api.github.com/users/mixa1901/repos',
              'events_url': 'https://api.github.com/users/mixa1901/events{/privacy}',
              'received_events_url': 'https://api.github.com/users/mixa1901/received_events',
              'type': 'User', 'site_admin': False, 'contributions': 2}]
